name: test

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v4

      - name: demo workflow job
      - run: echo This is a demo start workflow

      